import BaseLayout from "@/components/BaseLayout"
import Providers from "@/components/Providers"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Geist } from "next/font/google"
import { Toaster } from "sonner"
import "./globals.css"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "RGB Test Task",
  description: "Generated by create next app",
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/deal.png"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Providers>
          <BaseLayout>{children}</BaseLayout>
          <Toaster
            position="top-right"
            richColors
            closeButton
          />
        </Providers>
      </body>
    </html>
  )
}
